### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function socket_create()

### ISSUE THREAD

**Issue by ricardotulio** [tacnoman/dephpugger#21]
## Context
Problem when try to run `$ dephpugger debug` command.

## Expected behavior
Just work as needed.

## Current behavior
When I tried to run `$ dephpugger debug`, I receive the following message:

```
Fatal error: Uncaught Error: Call to undefined function Dephpug\Dbgp\socket_create()
```

It ocurr because `socket_create` inst imported in Dephpug/Dbgp/Server.php.

**Comment by tacnoman** [comment]
This problem occurs when php_sockets is not installed. The namespace `Dephpug\Dbgp\socket_create` is calling because they cannot call this function.

I will change the `socket_create` to `\socket_create` and add this lib in `requirements` command.

**Comment by ricardotulio** [comment]
@tacnoman yes, exactly, thanks! I have found the solution but didnt commente here, sorry.
