### ISSUE TITLE
Cant run requirements

### ISSUE THREAD

**Issue by liaogz82** [tacnoman/dephpugger#25]
Hi I need some help here. I run `dephpugger requirements` and this is what i get

```
Fatal error: Uncaught Error: Class 'Dephpug\Console\CliCommand' not found in /root/.composer/vendor/tacnoman/dephpugger/src/Dephpug/Dephpugger.php:28
Stack trace:
#0 /root/.composer/vendor/tacnoman/dephpugger/bin/dephpugger(48): Dephpug\Dephpugger->run()
#1 {main}
  thrown in /root/.composer/vendor/tacnoman/dephpugger/src/Dephpug/Dephpugger.php on line 28
The command '/bin/sh -c dephpugger requirements' returned a non-zero code: 255
```

any idea what is wrong?

**Comment by tacnoman** [comment]
Hello @liaogz82 
Sorry about my delay.

We had this problem versions ago. Are you using the latest version?

**Comment by liaogz82** [comment]
Yes I am sure the problem is still there. Check out
https://github.com/tacnoman/dephpugger/issues/26

**Comment by Lewiscowles1986** [comment]
Are we sure that it's not just composer not being up to date

**Comment by Lewiscowles1986** [comment]
maybe the bin file is just awful. Below works in a contrived environment (obviously not PR worthy) for #26 reddit `Dockerfile`

```
#!/usr/bin/env php
<?php

require_once '/root/.composer/vendor/autoload.php';

// Create application
$application = new Dephpug\Dephpugger();
$application->run();
```

As I can fathom it's failing to traverse.

`__DIR__` to find the `vendor` folder.

- it could be up one folder from `./bin` where it's housed without `vendor` in it's path `../vendor/autoload.php`
- it could be several folders up `../../../autoload.php`

`composer global dump-autoload` is also needed before running (don't worry about committing a `composer.json` skipping the step.

**Comment by Lewiscowles1986** [comment]
someone do me a favor and check out the following

```
#!/usr/bin/env php
<?php

$pathParts = explode(DIRECTORY_SEPARATOR, __DIR__);

function findInnerPart($search, $parts=[]) {
        do {
                $part = array_pop($parts);
        } while(($part != $search) && (count($parts) > 1));
        return implode(DIRECTORY_SEPARATOR, $parts);
}

$vendorPath = '';
if(in_array('vendor', $pathParts, true)) {
        $suffix = implode(DIRECTORY_SEPARATOR, ['', 'vendor']);
        $vendorPath = findInnerPart('vendor', $pathParts) . $suffix;
} else if(in_array('bin', $pathParts, true)) {
        $suffix = implode(DIRECTORY_SEPARATOR, ['', '..', 'vendor']);
        $vendorPath = findInnerPart('bin', $pathParts) . $suffix;
} else {
        exit("Can't find 'vendor' path.");
}

require_once implode(DIRECTORY_SEPARATOR, [$vendorPath, 'autoload.php']);

// Create application
$application = new Dephpug\Dephpugger();
$application->run();
```

Covers both cases. You can wrap part of it as a method and give it some table tests
