### ISSUE TITLE
Step up/down stack with u / d

### ISSUE THREAD

**Issue by Lewiscowles1986** [tacnoman/dephpugger#28]
I use `pdbpp` for python, and one of the most amazing features it has is the ability to use `u` and `d` keys to traverse the calls (I'm assuming this is stack walking, but may be wrong).

I don't expect this will get done, but I think it'd be a nice feature so maybe someone will see this and pick it up?

**Comment by tacnoman** [comment]
This feature should be amazing!
I need read the xDebug documentation to see if this exists in DBGP protocol

**Comment by tacnoman** [comment]
When xDebug implements this I should implement. Closed until wait this feature.

**Comment by Lewiscowles1986** [comment]
xDebug apparently does implement this. I found from Derrick Rethans, and confirmed that via Visual Studio code I could step up and down stack frames. It's there somewhere. How to access it I do not know
