### ISSUE TITLE
Update cboden/ratchet since it's current dependency guzzle/http is abandoned

### ISSUE THREAD

**Issue by ArtemGoutsoul** [tacnoman/dephpugger#32]
Should be updated since the version used now uses abandoned guzzle/http. Latest cboden/ratchet does not have that issue.

**Comment by tacnoman** [comment]
Thanks for this
I'll update all libs this week

**Comment by tacnoman** [comment]
Updated @ArtemGoutsoul 

I'll close a patch now.
Thanks for this
