### ISSUE TITLE
Dephpugger used to be able to work on drupal 8, now it can't

### ISSUE THREAD

**Issue by liaogz82** [tacnoman/dephpugger#34]
I used to be able to run dephpugger on drupal 8, and have wrote an [article](https://medium.com/@mosesliao/debug-drupal-using-dephpugger-a0839f878b56) on it. But now I tried to replicate its steps and it is not working anymore.

Have you changed anything to the source code since September 26 2018? Cos this debugging tool proves more useful to me than the rest of the normal debugging tool of drupal. It will do me wonders if you can get it working again. Thanks!

**Comment by tacnoman** [comment]
wooow!
Thanks for this man! I'll add this article in README @liaogz82
