### ISSUE TITLE
how to run PHP scripts with command-line arguments

### ISSUE THREAD

**Issue by skierpage** [tacnoman/dephpugger#42]
I'm trying to debug the command-line program invocation
``` lang=bash
$ /usr/share/arcanist/scripts/arcanist.php --trace install-certificate --conduit-uri=https://phabricator.kde.org/api/conduit.ping
```
I can't see how to provide command line arguments to the PHP script I supply to the `dephpugger cli` command. I've checked `dephpugger help cli` usage help and your online docs.

Update: it seems putting the PHP script and its command-line arguments in quotes as a single argument works. Please mention this to  https://dephpugger.com/docs/usage/commands_to_run and add to the usage for `dephpugger cli --help`  a line like

Arguments:
  file                  The php script file
  or 'file arg1 arg2 ...'   The php script file and its command-line arguments in quotes.

**Comment by indrisepos** [comment]
Check out: 
`dephpugger cli 'test.php param1 param2 param3'`

**Comment by tacnoman** [comment]
Thanks for this issue
I'll add this example in documentation :)
